"""Housekeeping tasks: budget reporting, docs generation, artifact sync.

``docs.build`` regenerates ``docs/EXPERIMENTS.md`` from the run manifests in ``runs/`` so
the experiment log is never hand-maintained (and therefore never stale). Sorted by CV log
loss, best first.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from . import budget as budget_mod
from .config import get_config
from .logging_utils import get_logger
from .paths import runs_dir
from .staging import restore_from_drive, sync_to_drive
from .tasks import task

log = get_logger("maintenance")


@task(
    "budget.report",
    requires="cpu",
    max_tier="h100",
    description="spend by task and tier against the configured unit balance",
)
def budget_report(force: bool = False, subsample: int | None = None) -> dict[str, Any]:
    rep = budget_mod.report()
    print(budget_mod.format_report(rep))
    return rep


def _iter_manifests() -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    root = runs_dir()
    if not root.is_dir():
        return out
    for task_dir in sorted(root.iterdir()):
        if not task_dir.is_dir():
            continue
        for p in sorted(task_dir.glob("*.json")):
            try:
                out.append(json.loads(p.read_text()))
            except (json.JSONDecodeError, OSError):
                continue
    return out


@task(
    "docs.build",
    requires="cpu",
    max_tier="cpu",
    description="regenerate docs/EXPERIMENTS.md from run manifests",
)
def docs_build(force: bool = False, subsample: int | None = None) -> dict[str, Any]:
    cfg = get_config()
    manifests = _iter_manifests()

    scored = []
    for m in manifests:
        metrics = m.get("metrics") or {}
        ll = metrics.get("logloss")
        if ll is None:
            continue
        scored.append(
            {
                "ts": m.get("ts", ""),
                "task": m.get("task", ""),
                "experiment": metrics.get("experiment", m.get("task", "")),
                "sha": m.get("git_sha", ""),
                "logloss": float(ll),
                "auc": metrics.get("auc"),
                "delta": metrics.get("delta_vs_lo_only"),
                "units": m.get("units", 0.0),
                "wall": m.get("wall_seconds", 0.0),
                "subsample": m.get("subsample"),
            }
        )
    scored.sort(key=lambda r: r["logloss"])

    # Scores from different subsample sizes are NOT comparable — a 400-session run and a
    # full 22,821-session run measure different problems. Separate tables so a small-subsample
    # number can never be mistaken for the leading result.
    def _dedup(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Collapse repeated reruns of the same experiment at the same score."""
        seen: set[tuple[str, float]] = set()
        out = []
        for r in rows:
            key = (r["experiment"], round(r["logloss"], 6))
            if key in seen:
                continue
            seen.add(key)
            out.append(r)
        return out

    full_runs = _dedup([r for r in scored if r["subsample"] is None])
    sub_runs = _dedup([r for r in scored if r["subsample"] is not None])

    def _rows(rows: list[dict[str, Any]], show_sub: bool = False) -> list[str]:
        out = []
        for i, r in enumerate(rows[:60], 1):
            delta = f"{r['delta']:+.5f}" if isinstance(r["delta"], int | float) else "—"
            auc = f"{r['auc']:.4f}" if isinstance(r["auc"], int | float) else "—"
            extra = f" {r['subsample']} |" if show_sub else ""
            out.append(
                f"| {i} | `{r['experiment']}` | **{r['logloss']:.5f}** | {delta} | {auc} | "
                f"{r['units']:.3f} | {r['wall']:.1f} |{extra} `{r['sha']}` | {r['ts'][:10]} |"
            )
        return out or ["| — | _no runs yet_ | | | | | | | |"]

    head = "| # | Experiment | CV log loss | Δ vs lo_only | AUC | Units | Wall (s) | SHA | Date |"
    sep = "|---|---|---|---|---|---|---|---|---|"

    lines = [
        "# EXPERIMENTS.md",
        "",
        "> **Auto-generated by `docs.build` from `runs/` — do not edit by hand.**",
        f"> Last generated: {datetime.now(UTC).isoformat(timespec='seconds')}",
        "",
        "Sorted by CV log loss (lower is better). `Δ vs lo_only` is **negative when the model",
        "beats** the learning-objective-only baseline — the organizers' stated anti-goal.",
        "",
        "## Full-data runs — the only comparable table",
        "",
        head,
        sep,
        *_rows(full_runs),
        "",
        "## Subsampled runs — smoke tests, NOT comparable",
        "",
        "Computed on a fraction of the sessions; they exist only to prove the pipeline runs.",
        "Never quote one as a result.",
        "",
        head.replace("| Wall (s) |", "| Wall (s) | Subsample |"),
        sep + "---|",
        *_rows(sub_runs, show_sub=True),
    ]

    rep = budget_mod.report()
    lines += [
        "",
        "## Compute spend",
        "",
        f"- Configured balance: **{rep['total_units_configured']:.0f} units**",
        f"- Spent: **{rep['units_spent']:.2f}** across {rep['n_runs']} runs",
        f"- Remaining: **{rep['units_remaining']:.2f}**",
        "",
        "| Tier | Units |",
        "|---|---|",
    ]
    for tier, u in rep["by_tier"].items():
        lines.append(f"| {tier} | {u:.3f} |")

    dest = cfg.repo_dir / "docs" / "EXPERIMENTS.md"
    dest.write_text("\n".join(lines) + "\n")
    log.info("docs.build: wrote %s (%d scored runs)", dest, len(scored))
    return {
        "output_path": str(dest),
        "n_scored_runs": len(scored),
        "best_logloss": scored[0]["logloss"] if scored else None,
    }


@task(
    "maintenance.sync_artifacts",
    requires="cpu",
    max_tier="h100",
    description="tar artifacts + runs and push them to Drive (single large write)",
)
def sync_artifacts(force: bool = False, subsample: int | None = None) -> dict[str, Any]:
    """Push artifacts and run manifests to Drive as tarballs.

    Tarring first is deliberate: Drive is a FUSE mount, so we write a handful of large
    files rather than walking a directory tree over it.
    """
    cfg = get_config()
    written: list[str] = []
    for local_rel, drive_rel in (
        ("artifacts", "artifacts/rollup.tar"),
        ("runs", "runs/runs.tar"),
        # Paid embedding outputs are feature caches, not model artifacts. Omitting these
        # meant an L4 disconnect discarded the expensive extraction despite "cache forever"
        # messaging throughout the runbook.
        ("data/features", "cache/features.tar"),
        ("data/interim", "cache/interim.tar"),
    ):
        local = cfg.work_dir / local_rel
        if not local.exists():
            continue
        dest = sync_to_drive(local, drive_rel, as_tar=True)
        if dest is not None:
            written.append(str(dest))
    if not written:
        log.info("sync_artifacts: local mode (no Drive configured) — nothing synced")
    return {"synced": written, "n_synced": len(written)}


@task(
    "maintenance.restore_artifacts",
    requires="cpu",
    max_tier="h100",
    description="restore model/run/feature caches from Drive tarballs",
)
def restore_artifacts(force: bool = False, subsample: int | None = None) -> dict[str, Any]:
    restored = [
        str(path)
        for drive_rel in (
            "artifacts/rollup.tar",
            "runs/runs.tar",
            "cache/features.tar",
            "cache/interim.tar",
        )
        if (
            path := restore_from_drive(
                drive_rel,
                force=force,
                destination_parent="data" if drive_rel.startswith("cache/") else None,
            )
        )
        is not None
    ]
    return {"restored": restored, "n_restored": len(restored)}


def artifacts_dir(config: Any = None) -> Path:
    """Convenience accessor used by the notebook close-out cell."""
    return get_config().work_dir / "artifacts"
